module.exports = {
  RENDER_DIST: 600,
  TILE_DIST: 6,
  FADE_RANGE: 20,
  PLAYER_SPEED: 200,
  MAP_SIZE: 100 * 32,
  KEYBINDS: {
    WORLD_ROTATE_CW: 'KeyE',
    WORLD_ROTATE_CCW: 'KeyQ',
    WORLD_TILT_UP: 'KeyX',
    WORLD_TILT_DOWN: 'KeyZ',
    WORLD_RESET_PERSPECTIVE: 'KeyR',
    PLAYER_UP: 'KeyW',
    PLAYER_DOWN: 'KeyS',
    PLAYER_LEFT: 'KeyA',
    PLAYER_RIGHT: 'KeyD',
  }
};